[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "7d7b92bfb71738656936075d4f3f29e94ffada8a"
os = "macos"

    [[libsparseir.download]]
    sha256 = "42ae3929ced200dad1c7f1346615c2e280c87ce70cb375c90a0895b46270787b"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+1/libsparseir.v0.8.4.aarch64-apple-darwin.tar.gz"
[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "becc902d148a1457e87c3da5830d8527a01b1776"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "ad80b789c77df315ae305e64af6bcfce5b40a3bf5df3aa363bb6c63da9449bc7"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+1/libsparseir.v0.8.4.aarch64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "powerpc64le"
git-tree-sha1 = "ee91d9024f1518e46e1545320cd70449c88af871"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "b4895ce7f30b019348065bbc66fe69e23fefaf989e69ee88646f55b4c4c7259f"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+1/libsparseir.v0.8.4.powerpc64le-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "f07e576e0fa39f843d0d2473c25c97e19677fe66"
os = "macos"

    [[libsparseir.download]]
    sha256 = "c303e190152f6f062a898ae602b62c6986b267f3765614d1c9134dd39be8f8b0"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+1/libsparseir.v0.8.4.x86_64-apple-darwin.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "c06d798b05f4ff33682cc66b6b5b213a9d129787"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "e677249cc5ee42ea15be70b3888512cfc1d8ac2c2dbbd2c6f738b4a483b70a52"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+1/libsparseir.v0.8.4.x86_64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "aa94f93387531e349cc0893b1c2f677703c24d2a"
os = "freebsd"

    [[libsparseir.download]]
    sha256 = "b05da9b63c35646dee9b9a4b0438dc1bbed5ad5c77144f5f90f4199396c078ad"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+1/libsparseir.v0.8.4.x86_64-unknown-freebsd.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "6199ac59ea5b04015332688f944f3bf91b017c73"
os = "windows"

    [[libsparseir.download]]
    sha256 = "b46f826363e8a07141f1af9d1984118113e99a18e27cea428db1321531d108fe"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+1/libsparseir.v0.8.4.x86_64-w64-mingw32.tar.gz"
