[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "6581ceb75a25801013bd5fd80fecea48286e28b0"
os = "macos"

    [[libsparseir.download]]
    sha256 = "e602428624ef02646559f33f1b9c42b76c5dc068e2ba726959e72c24a52abe2f"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+0/libsparseir.v0.8.4.aarch64-apple-darwin.tar.gz"
[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "538e98cc4f91a9a2ef62b0ff836a784e8776dd28"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "6d9520ad2162c6c43f5dc2e648d60fe1ff50357481b314a9ba063812b7bbcbcb"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+0/libsparseir.v0.8.4.aarch64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "powerpc64le"
git-tree-sha1 = "90ee9deaa8da1ce01a54fbfa1292c13a19b7c6c8"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "14b89d1a2f9a5c55dfb2ba615d9c2be326090329d0ddd22126539ff8465fb735"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+0/libsparseir.v0.8.4.powerpc64le-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "45ebfa1cd9495a0100ac5f2a077b0f704e7ac9cf"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "3c178d53b9750c5d44ae4825add735c00da215f85e70e9ef8e7462af3d89ace9"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+0/libsparseir.v0.8.4.x86_64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "f830f53ab52f32075fe598e9c582c64345e0d37a"
os = "freebsd"

    [[libsparseir.download]]
    sha256 = "38bf39a3d1edae882eb98b8d81eef00b8f35302450746c809937b9ff57e7e13d"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+0/libsparseir.v0.8.4.x86_64-unknown-freebsd.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "57a2603d5ab0489e395d68b1aa65992279db9612"
os = "windows"

    [[libsparseir.download]]
    sha256 = "0b5d10568eb6d24f2c53abcdcbd3c1be5b759d7aa2d8844067cfc29cdf8ea34c"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.4+0/libsparseir.v0.8.4.x86_64-w64-mingw32.tar.gz"
